# Generated by Django 3.2.3 on 2022-01-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymembers',
            name='g_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='794e715dc3dc47399d225220c1cbcda1', max_length=100, unique=True, verbose_name='نام کاربری'),
        ),
    ]
