# Generated by Django 3.2.3 on 2021-12-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingverify',
            old_name='allowed_try_count',
            new_name='allowed_try',
        ),
        migrations.RemoveField(
            model_name='pendingverify',
            name='email',
        ),
        migrations.AddField(
            model_name='pendingverify',
            name='receptor',
            field=models.EmailField(default='a@a.com', max_length=50, primary_key=True, serialize=False, verbose_name='دریافت کننده'),
        ),
        migrations.AlterField(
            model_name='pendingverify',
            name='otp',
            field=models.IntegerField(verbose_name='OTP کد'),
        ),
    ]
