# Generated by Django 3.2.3 on 2021-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='Fr',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='Mo',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='Sa',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='Su',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='Th',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='Tu',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
        migrations.AlterField(
            model_name='gatheringscheduall',
            name='We',
            field=models.SmallIntegerField(choices=[('0', 'active with out repeat'), ('1', 'repeat'), ('2', 'unactive')]),
        ),
    ]
