# Generated by Django 3.2.3 on 2022-04-05 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hangoutinvitation',
            options={'verbose_name': 'درخواست افزودن به پاتوق', 'verbose_name_plural': 'درخواست های افزودن به پاتوق'},
        ),
        migrations.AlterModelOptions(
            name='usershavefriends',
            options={'ordering': ['time'], 'verbose_name': 'وضعیت درخواست دوستی', 'verbose_name_plural': 'وضعیت درخواست های دوستی'},
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'زن'), ('m', 'مرد')], max_length=6, null=True, verbose_name='جنسیت'),
        ),
        migrations.CreateModel(
            name='HangoutRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', 'پاسخ داده شده'), ('w', 'در انتظار')], max_length=1, null=True, verbose_name='وضعیت')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('hangout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.hangout', verbose_name='پاتوق')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
            ],
            options={
                'verbose_name': 'درخواست اضافه شدن به پاتوق',
                'verbose_name_plural': 'درخواست های اضافه شدن به پاتوق',
                'ordering': ['datetime'],
                'unique_together': {('hangout', 'sender')},
            },
        ),
    ]
