# Generated by Django 3.2.3 on 2022-01-30 12:59

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=main_app.models.generate_random_username, max_length=100, unique=True, verbose_name='نام کاربری'),
        ),
    ]
