# Generated by Django 3.2.3 on 2022-02-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patoghinfo',
            options={'ordering': ['id'], 'verbose_name': 'اطلاعات دورهمی', 'verbose_name_plural': 'اطلاعات دورهمی ها'},
        ),
        migrations.AlterField(
            model_name='patoghinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.patoghcategory', verbose_name='نوع پاتوق'),
        ),
        migrations.AlterField(
            model_name='patoghinfo',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation time for the patogh', null=True, verbose_name='زمان ساخت پاتوق'),
        ),
    ]
