# Generated by Django 3.2.9 on 2022-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220113_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(blank=True, through='main_app.PartyMembers', to='main_app.Party'),
        ),
    ]
