# Generated by Django 3.2.3 on 2022-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220405_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='hangoutrequests',
            name='status',
        ),
        migrations.DeleteModel(
            name='UsersHaveFriends',
        ),
    ]
