# Generated by Django 3.2.3 on 2022-03-07 14:47

import django.core.validators
from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG, JPEG or PNG is validate', null=True, upload_to=main_app.models.party_image_profile_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), main_app.models.validate_image_size], verbose_name='عکس اکیپ'),
        ),
    ]
