# Generated by Django 3.2.3 on 2022-01-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220125_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parties',
            field=models.ManyToManyField(blank=True, through='main_app.PartyMembers', to='main_app.Party'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام کاربری'),
        ),
    ]
