# Generated by Django 3.2.3 on 2022-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220405_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangout',
            name='gender',
            field=models.CharField(choices=[('male', 'پسر'), ('female', 'دختر'), ('both', 'مختلط')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='place',
            field=models.CharField(blank=True, choices=[('park', 'پارک'), ('museum', 'موزه'), ('cafe', 'کافه'), ('restaurant', 'رستوران '), ('cinema', 'سینما')], max_length=40, null=True, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='province',
            field=models.CharField(choices=[('azr-e', 'آذربایجان شرقی'), ('azr-w', 'آذربایجان غربی'), ('ardabil', 'اردبیل'), ('esfahan', 'اصفهان'), ('alborz', 'البرز'), ('ilam', 'ایلام'), ('bushehr', 'بوشهر'), ('tehran', 'تهران'), ('charmahal', 'چهارمحال و بختیاری'), ('khor-s', 'خراسان جنوبی'), ('khor-n', 'خراسان شمالی'), ('khor-r', 'خراسان رضوی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kordestan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiloye', 'کهگیلویه و بویر احمد'), ('golestan', 'گلستان'), ('gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamedan', 'همدان'), ('yazd', 'یزد')], max_length=20, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='repeat',
            field=models.CharField(blank=True, choices=[('none', 'هیچکدام'), ('weekly', 'هر هفته'), ('monthly', 'هر ماه')], default='n', max_length=20, null=True, verbose_name='تکرار'),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='status',
            field=models.CharField(choices=[('private', 'خصوصی'), ('public', 'عمومی')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='hangout',
            name='type',
            field=models.CharField(blank=True, choices=[('scientific', 'علمی'), ('athletic', 'ورزشی'), ('artistic', 'هنری')], max_length=30, null=True, verbose_name='نوع پاتوق'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'زن'), ('male', 'مرد')], max_length=6, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, choices=[('azr-e', 'آذربایجان شرقی'), ('azr-w', 'آذربایجان غربی'), ('ardabil', 'اردبیل'), ('esfahan', 'اصفهان'), ('alborz', 'البرز'), ('ilam', 'ایلام'), ('bushehr', 'بوشهر'), ('tehran', 'تهران'), ('charmahal', 'چهارمحال و بختیاری'), ('khor-s', 'خراسان جنوبی'), ('khor-n', 'خراسان شمالی'), ('khor-r', 'خراسان رضوی'), ('khuzestan', 'خوزستان'), ('zanjan', 'زنجان'), ('semnan', 'سمنان'), ('sistan', 'سیستان و بلوچستان'), ('fars', 'فارس'), ('qazvin', 'قزوین'), ('qom', 'قم'), ('kordestan', 'کردستان'), ('kerman', 'کرمان'), ('kermanshah', 'کرمانشاه'), ('kohgiloye', 'کهگیلویه و بویر احمد'), ('golestan', 'گلستان'), ('gilan', 'گیلان'), ('lorestan', 'لرستان'), ('mazandaran', 'مازندران'), ('markazi', 'مرکزی'), ('hormozgan', 'هرمزگان'), ('hamedan', 'همدان'), ('yazd', 'یزد')], max_length=20, null=True, verbose_name='استان'),
        ),
    ]
